name: LegacyMinecraftPinger
author: RhysB
website: github.com/rhysb
main: com.johnymuffin.beta.legacyminecraft.pinger.LegacyMinecraftPinger
version: ${project.version}
visible: false
softdepend:
  - BetaCraftPing #This is here to ensure accuracy when checking to see if BetaCraftPing is installed